### ISSUE TITLE
Current blame line and linechars are hard to see

### ISSUE THREAD

**Issue by msmirnov-godaddy** [sthendev/mariana.vim#9]
Is it possible to change current blame line and the color of `linechars` to the same color as the comments?

```
vim.cmd[[set listchars=tab:→\ ,eol:↲,nbsp:␣,trail:•,extends:⟩,precedes:⟨]]
```
<img width="1628" alt="Screen Shot 2021-12-20 at 3 45 31 PM" src="https://user-images.githubusercontent.com/89097066/146847620-9193dff5-3622-4998-8ac0-eb4a1fff11c2.png">

For example, here is what it looks like in gruvbox:
<img width="1256" alt="Screen Shot 2021-12-20 at 3 51 07 PM" src="https://user-images.githubusercontent.com/89097066/146847763-6b760c71-8b60-4944-b6db-373a1cbcbe1c.png">

Thanks!

**Comment by sthendev** [comment]
Sorry for the late response. I have updated the highlights that were previously dark grey to a more visible color.

![image](https://user-images.githubusercontent.com/37766610/184486338-bbd74e2f-a2ca-4b1d-a49f-6a623ede2683.png)

As for blame lines. I am not sure what plugin you are using to get blame lines. The one I tried out (see screenshot) defaults to the 'Comment' highlight group and provides the option to change the highlight group as well. Maybe see if your plugin has similar configuration options.
